apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: rancher
  labels:
    app: rancher
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: web
    targetPort: 443
  selector:
    app: rancher