apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  namespace: rancher
spec:
  selector:
    matchLabels:
      app: rancher
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rancher
    spec:
      containers:
      - name: rancher-server
        imagePullPolicy: IfNotPresent
        image: rancher/rancher
        ports:
          - containerPort: 443
        volumeMounts:
         - name: rancher-data
           mountPath: /var/lib/rancher
      volumes:
        - name: rancher-data
          nfs:
            server: nfs-server
            path: /mnt/nfs/rancher/data/